<h5>General Settings</h5>
<p>App name, company name, logo (also favicon), timezone, and region. Admin: <code>/admin/system/general</code> (administrators).</p>
<p><strong>Reading (homepage &amp; blog):</strong> Choose a static front page or latest posts, pick which published page is the homepage, and set posts per page (paginated blog). WordPress-style <code>Settings → Reading</code> equivalent in General settings.</p>
<p><strong>Discussion:</strong> Enable comments on posts, require moderation, name/email requirements, and show the sidebar widget area on public pages.</p>
<p><strong>Newsletter:</strong> Allow public signups, require a confirmation email (double opt-in), and cap attempts per IP. Visitors use <code>/subscribe</code> or the Newsletter widget. The list is Content → Subscribers. Confirm mail uses Email settings.</p>
<p><strong>Permalinks:</strong> Custom URL patterns for pages (default <code>/p/slug</code> or plain <code>/slug</code>) and posts (default <code>/blog/slug</code>, plain, year/month, or category-based). Default routes always remain available.</p>
<p><strong>Google (Analytics, Ads, Search):</strong> Paste IDs only — never raw script snippets. <strong>GA4</strong> measurement ID (<code>G-…</code>, or legacy <code>UA-…</code>), <strong>Google Ads</strong> (<code>AW-…</code>), <strong>AdSense</strong> publisher (<code>ca-pub-…</code>), and optional <strong>Programmable Search</strong> engine ID. Search Console verification is the HTML-tag <code>content</code> value only (same key as before). Invalid IDs are ignored on save. The public site loads Google’s official scripts; theme preview and the Customizer iframe do not. After verification, add <code>/sitemap.xml</code> in Search Console. Programmable Search adds Google results on public <code>/search</code> below the built-in CMS results.</p>
<p><strong>Public site theme:</strong> Large set of live options under <strong>Appearance → Customize</strong> (presets including <strong>Editorial (crimson)</strong>, typography, nav/blog/layout, motion, focus, visibility toggles). <strong>Editorial magazine:</strong> optional style pack, chrome mode, blog kicker, readable dates, company tagline. Bundled zips include Sample template, Play · Build · Sound, <strong>Manly</strong> (dark oak/leather), <strong>Pulse</strong> (teal civic look with header/homepage widgets), <strong>Enterprise</strong>, and <strong>The Filipino Men</strong> (warm paper journal for everyday manhood; seed with <code>php cli/seed_filipino_men_site.php</code>; import essays via Posts → Import or <code>php cli/import_atom_feed.php</code>). Blog listing supports <strong>list / grid / cards / magazine / compact</strong>. Same fields also on System → General. For a magazine homepage, set Reading to <strong>Your latest posts</strong>.</p>
<p><strong>Site-wide SEO &amp; LLM:</strong> Default meta description, title suffix, default Open Graph image, Twitter handle, Facebook/LinkedIn/Reddit/YouTube URLs (Schema.org <code>sameAs</code>), locale, keywords, LLM site summary, and toggles for <code>/sitemap.xml</code>, <code>/feed.xml</code> (RSS), JSON exports (<code>/site.json</code>, <code>/blog.json</code>), <code>/llms.txt</code>, and allowing AI crawlers in <code>robots.txt</code>. Google Search Console verification lives under <strong>Google</strong> above. Public site search is <code>/search</code> (pages and posts; password-protected items are omitted). Per-page and per-post SEO fields override these defaults. Individual pages and posts can require a visitor password (body hidden until unlock).</p>
<p><strong>AI search &amp; citation:</strong> Publisher expertise (E-E-A-T), preferred citation line, citation guidance, topic cluster / pillar subjects, FAQPage schema toggle, speakable citation snippets, and optional writing tips on page/post editors. These feed <code>/llms.txt</code>, <code>/site.json</code>, and Organization JSON-LD so assistants can extract and cite passage-level answers.</p>
