<h5>Posts</h5>
<p>Write blog posts with excerpt, category, featured image, optional <strong>visual layout builder</strong> (frontend editor — modules include heading, text, image, <strong>carousel</strong>, button, CTA, blurb, and more) and optional <strong>block builder</strong>, tags (comma-separated), publish date, and optional <strong>content width</strong> override for the public post layout. Visual layout takes precedence over blocks and body when saved. When a visual layout is saved, the public post does <strong>not</strong> repeat the title or featured image above the layout (those stay for the blog list, SEO, and social sharing). In the frontend editor: use <strong>Desktop / Tablet / Mobile</strong> preview (and the same buttons to edit tablet/mobile Design), <strong>Templates</strong> to reuse layouts, <strong>Layers</strong> (with a filter; drag to reorder) for the structure tree, choose column layouts per row, add modules from the described side-panel picker (or <strong>+</strong> after a module), edit Content / Design / Advanced (Content shows the fields for that module type, including carousel slides; Design colors can use theme tokens; sections can set a background image and overlay; module Design has Normal / Hover, border/corners/shadow, and Copy style / Paste style; Content edits update the selected module without a full canvas rebuild), type heading/text on the canvas, <strong>Copy</strong> / <strong>Paste</strong> (Ctrl/Cmd+C / V or right-click), press <strong>?</strong> for shortcuts, drag <strong>⋮⋮</strong> to reorder, and set column <strong>width (1–12)</strong> and <strong>min height</strong> (or drag the column edge). Design colors, spacing, and min height apply live without rebuilding the canvas. Inspector crumbs jump to a parent section/row/column. <strong>Undo / Redo</strong> (Ctrl/Cmd+Z / Y), Ctrl/Cmd+S save, Ctrl/Cmd+D duplicate; dirty layouts autosave about every 12 seconds. Button and CTA modules can open links in a new tab. <strong>Revisions</strong> appear on the post view screen for rollback. Published posts appear on <code>/blog</code> (listing layout — list/grid/cards/magazine/compact, columns, and visitor view switcher — under Appearance → Customize or System → General → Public site theme).</p>
<p><strong>Create everything on the form:</strong> Upload featured or block images here; click tag chips or type new tag names (auto-created); add a new category without leaving the editor.</p>
<p><strong>SEO &amp; social:</strong> SEO title, meta description (150–160 chars), featured share image (1200×630 recommended), optional <code>noindex</code>, and <strong>content width</strong> override (full / wide / normal / narrow) for the public post layout.</p>
<p><strong>LLM / AI:</strong> Plain-language summary for assistants; JSON at <code>/blog/{slug}.json</code>; Schema.org <code>BlogPosting</code> on the public HTML. Listed in <code>/llms.txt</code> when published and not noindex.</p>
<p><strong>Citation / BLUF:</strong> One-sentence citation snippet for AI passage extraction; optional FAQ Q&amp;A pairs for Schema.org <code>FAQPage</code>. Site-wide citation policy: System → General → AI search &amp; citation.</p>
<p><strong>Comments:</strong> Visitors can leave comments when enabled under General → Discussion. Moderate under <code>/admin/comments</code>.</p>
<p><strong>Featured image:</strong> Upload or pick on the post form. Used on the blog listing and as Open Graph / Twitter Card image. Recommended size: <strong>1200×630 px</strong>. Public URL: <code>/share/media/{id}</code>.</p>
<p>Admin: <code>/admin/posts</code></p>
<p><strong>Visual builder demo:</strong> <code>npm run test:e2e:cms-builder-drag-column-size</code> (headed) shows drag reorder, column width 1–12, edge resize, and min height on a published page. Same builder is used for posts via <strong>Edit via Frontend editor</strong>.</p>
<p><strong>While logged in:</strong> Public post pages show <strong>Edit via Frontend editor</strong> and <strong>Edit in admin</strong> for users with <code>edit_posts</code>.</p>
